version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    env_file:
      - ../backend/.env
    depends_on:
      - chromadb
    volumes:
      - backend_storage:/app/storage

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/chroma

volumes:
  chromadb_data:
  backend_storage:
