"""Add Supabase and pgvector models

Revision ID: 06a7ec88d702
Revises: 043db5d15038
Create Date: 2026-08-15 14:16:05.595521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06a7ec88d702'
down_revision: Union[str, Sequence[str], None] = '043db5d15038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_artifacts', sa.Column('storage_path', sa.String(), nullable=True))
    op.add_column('extraction_artifacts', sa.Column('storage_path', sa.String(), nullable=True))
    op.add_column('paper_section_vectors', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('paper_section_vectors', sa.Column('metadata_json', sa.Text(), nullable=False))
    op.alter_column('paper_section_vectors', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('paper_section_vectors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_paper_section_vectors_id'), 'paper_section_vectors', ['id'], unique=False)
    op.drop_column('paper_section_vectors', 'title')
    op.drop_column('paper_section_vectors', 'source')
    op.drop_column('paper_section_vectors', 'section')
    op.drop_column('paper_section_vectors', 'year')
    op.drop_column('paper_section_vectors', 'content')
    op.drop_column('paper_section_vectors', 'paper_id')
    op.add_column('reports', sa.Column('storage_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'storage_path')
    op.add_column('paper_section_vectors', sa.Column('paper_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('paper_section_vectors', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('paper_section_vectors', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('paper_section_vectors', sa.Column('section', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('paper_section_vectors', sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('paper_section_vectors', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_paper_section_vectors_id'), table_name='paper_section_vectors')
    op.alter_column('paper_section_vectors', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('paper_section_vectors', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('paper_section_vectors', 'metadata_json')
    op.drop_column('paper_section_vectors', 'text')
    op.drop_column('extraction_artifacts', 'storage_path')
    op.drop_column('download_artifacts', 'storage_path')
    # ### end Alembic commands ###
