"""Add session_id to pipeline_runs

Revision ID: 7682ef2360c0
Revises: ae2e7be8c396
Create Date: 2026-08-16 23:30:49.845369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7682ef2360c0'
down_revision: Union[str, Sequence[str], None] = 'ae2e7be8c396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_pipeline_runs_session_id'), 'pipeline_runs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_session_id'), table_name='pipeline_runs')
    op.drop_column('pipeline_runs', 'session_id')
    # ### end Alembic commands ###
