"""remove unique from project name

Revision ID: a6d05b032bc0
Revises: 7be96846b723
Create Date: 2026-07-30 20:24:16.472054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d05b032bc0'
down_revision: Union[str, Sequence[str], None] = '7be96846b723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=1)

    # ### end Alembic commands ###
