"""Add events_json to PipelineRunRow

Revision ID: ae2e7be8c396
Revises: 06a7ec88d702
Create Date: 2026-08-15 20:02:44.076771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2e7be8c396'
down_revision: Union[str, Sequence[str], None] = '06a7ec88d702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs') as batch_op:
        batch_op.add_column(sa.Column('events_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'events_json')
    # ### end Alembic commands ###
