"""Add robustness fields to pipeline run

Revision ID: c7c9374ec07a
Revises: 7682ef2360c0
Create Date: 2026-08-17 14:43:44.056128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c9374ec07a'
down_revision: Union[str, Sequence[str], None] = '7682ef2360c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('step_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('step_progress_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('step_statuses_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_counter', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_column('heartbeat_counter')
        batch_op.drop_column('step_statuses_json')
        batch_op.drop_column('step_progress_json')
        batch_op.drop_column('step_started_at')
        batch_op.drop_column('last_updated_at')

    # ### end Alembic commands ###
