"""init schema

Revision ID: cf1d828025e7
Revises: 
Create Date: 2026-08-14 05:20:05.920706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1d828025e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors_json', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_index(op.f('ix_papers_paper_id'), 'papers', ['paper_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('steps_json', sa.Text(), nullable=False),
    sa.Column('papers_found', sa.Integer(), nullable=True),
    sa.Column('papers_downloaded', sa.Integer(), nullable=True),
    sa.Column('papers_extracted', sa.Integer(), nullable=True),
    sa.Column('papers_mined', sa.Integer(), nullable=True),
    sa.Column('papers_indexed', sa.Integer(), nullable=True),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_pipeline_runs_run_id'), 'pipeline_runs', ['run_id'], unique=False)
    op.create_table('download_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.String(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_artifacts_id'), 'download_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_download_artifacts_paper_id'), 'download_artifacts', ['paper_id'], unique=True)
    op.create_table('extraction_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.String(), nullable=True),
    sa.Column('raw_text_path', sa.String(), nullable=False),
    sa.Column('sections_path', sa.String(), nullable=True),
    sa.Column('extracted_chars', sa.Integer(), nullable=False),
    sa.Column('sections_found_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_artifacts_id'), 'extraction_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_extraction_artifacts_paper_id'), 'extraction_artifacts', ['paper_id'], unique=True)
    op.create_table('gap_signals',
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('paper_id', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_noise', sa.Boolean(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_gap_signals_paper_id'), 'gap_signals', ['paper_id'], unique=False)
    op.create_index(op.f('ix_gap_signals_signal_id'), 'gap_signals', ['signal_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('paper_ids_json', sa.Text(), nullable=False),
    sa.Column('report_json_path', sa.String(), nullable=True),
    sa.Column('report_md_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_gap_signals_signal_id'), table_name='gap_signals')
    op.drop_index(op.f('ix_gap_signals_paper_id'), table_name='gap_signals')
    op.drop_table('gap_signals')
    op.drop_index(op.f('ix_extraction_artifacts_paper_id'), table_name='extraction_artifacts')
    op.drop_index(op.f('ix_extraction_artifacts_id'), table_name='extraction_artifacts')
    op.drop_table('extraction_artifacts')
    op.drop_index(op.f('ix_download_artifacts_paper_id'), table_name='download_artifacts')
    op.drop_index(op.f('ix_download_artifacts_id'), table_name='download_artifacts')
    op.drop_table('download_artifacts')
    op.drop_index(op.f('ix_pipeline_runs_run_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_papers_paper_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
