import { ResearchInsight } from '../types';
import { Lightbulb, Compass, AlertTriangle } from 'lucide-react';
import { CopyButton } from '@/components/ui/CopyButton';

interface InsightCardProps {
  insight: ResearchInsight;
}

export function InsightCard({ insight }: InsightCardProps) {
  const insightText = `AI Insight: ${insight.summary}\n\nFuture Directions:\n${insight.future_directions.map(d => `- ${d}`).join('\n')}\n\nLimitations:\n${insight.limitations.map(l => `- ${l}`).join('\n')}`;

  return (
    <div className="bg-surface rounded-xl shadow-sm border border-indigo-200 p-6 mb-8 overflow-hidden relative">
      <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-50 rounded-bl-full -mr-16 -mt-16 z-0"></div>
      
      <div className="relative z-10">
        <div className="flex items-center gap-2 mb-4">
          <div className="bg-indigo-100 p-2 rounded-lg text-indigo-700">
            <Lightbulb className="w-5 h-5" />
          </div>
          <h2 className="text-xl font-bold text-gray-900">AI Synthesized Insight</h2>
          <CopyButton text={insightText} className="ml-2" label="Copy Insight" />
          <span className="ml-auto text-xs font-medium text-gray-400 bg-gray-100 px-2 py-1 rounded-full">
            Generated by {insight.model_name}
          </span>
        </div>
        
        <p className="text-gray-700 text-lg mb-6 leading-relaxed">
          {insight.summary}
        </p>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-indigo-50/50 rounded-lg p-4 border border-indigo-100">
            <h4 className="text-sm font-bold text-indigo-900 mb-3 flex items-center">
              <Compass className="w-4 h-4 mr-2" />
              Future Directions
            </h4>
            <ul className="space-y-2 text-sm text-indigo-800">
              {insight.future_directions.map((direction, idx) => (
                <li key={idx} className="flex items-start">
                  <span className="mr-2 mt-0.5">•</span>
                  <span>{direction}</span>
                </li>
              ))}
            </ul>
          </div>
          
          <div className="bg-orange-50/50 rounded-lg p-4 border border-orange-100">
            <h4 className="text-sm font-bold text-orange-900 mb-3 flex items-center">
              <AlertTriangle className="w-4 h-4 mr-2" />
              Known Limitations
            </h4>
            <ul className="space-y-2 text-sm text-orange-800">
              {insight.limitations.map((limit, idx) => (
                <li key={idx} className="flex items-start">
                  <span className="mr-2 mt-0.5">•</span>
                  <span>{limit}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
