from dataclasses import dataclass
from datetime import datetime
from typing import List

@dataclass
class ResearchInsight:
    """Represents a structured reasoning insight generated by the LLM."""
    gap_id: str
    summary: str
    research_opportunities: List[str]
    future_directions: List[str]
    limitations: List[str]
    generated_at: datetime
    model_name: str
