from dataclasses import dataclass
from datetime import datetime
from typing import List

@dataclass
class LLMTopicRefinement:
    """Represents a human-readable topic generated by the LLM."""
    name: str
    description: str
    keywords: List[str]

@dataclass
class LLMKeyFinding:
    title: str
    description: str
    importance: str

@dataclass
class LLMGapRefinement:
    """Represents a highly rigorous gap output by the LLM."""
    gap_id: str
    title: str
    description: str
    reasoning: str
    future_directions: List[str]

@dataclass
class LLMExecutiveSummary:
    """Represents the global executive summary synthesized by the LLM."""
    text: str
    key_findings: List[LLMKeyFinding]
